# Generated by Django 3.1.1 on 2020-09-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Date_de_naissance', models.DateField(default='1990-01-01')),
                ('Num_tel', models.IntegerField(max_length=8, unique=True)),
                ('Disponibilite', models.PositiveIntegerField()),
                ('Experience', models.PositiveIntegerField()),
                ('Cv', models.FileField(upload_to='')),
                ('Message', models.TextField()),
            ],
        ),
    ]
