# Generated by Django 3.1.1 on 2020-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_de_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Disponibilite',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Message',
            field=models.TextField(null=True),
        ),
    ]
