# Generated by Django 3.1.1 on 2020-09-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200902_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Etat',
            field=models.TextField(default='Nouvelle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Cv',
            field=models.TextField(null=True),
        ),
    ]
