# Generated by Django 3.1.1 on 2020-09-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200906_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Etat',
            field=models.TextField(default='Nouvelle', max_length=30),
        ),
    ]
